name: AeterumGods
version: '${project.version}'
main: me.figgnus.aeterumgods.AeterumGods
api-version: '1.20'
softdepend: [Brewery]
commands:
  tame:
    description: "Gives player a specific item to tame a horse"
    usage: /tame <item>
    permission: aeterumgods.tame.admin
    permission-message: "You don't have permission to use this command."
  ag:
    description: "Gives player a specific item"
    usage: /ag <item>
    permission: aeterumgods.item.admin
    permission-message: "You don't have permission to use this command."
  nightvision:
    description: "Gives player with permission ability to toggle night vision"
    usage: /<command>
  dolphingrace:
    description: "Toggles dolphin's grace effect"
    usage: /<command>
  randomizer:
    description: "Gives player randomizer tool"
    usage: /<command>



